language: java

dist: bionic

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - jdk_switcher use oraclejdk8
  - mvn clean package

before_install:
  - echo $LANG
  - echo $LC_ALL

os:
  - linux

branches:
  only:
    - master

notifications:
  email: true

